### ISSUE TITLE
Transifex collaborators limit reached

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/i18n#14]
![image](https://user-images.githubusercontent.com/1173416/195149044-9cc09e76-03e2-4828-8334-25a2c2bb6f6c.png)

Not sure that this is a high priority right now, but I figured I should bring attention to this. Here are a few action items I can think of for this:

- [ ] Remove inactive collaborators
- [ ] Audit settings so that users who don't assist with translation (me) aren't listed as collaborators, but can still perform administrative functions

**Comment by lidel** [comment]
This happens few times a year.  

I usually log-in to Transifex  and go over https://www.transifex.com/ipfs/reports/ and https://www.transifex.com/ipfs/teams/  which have >10 or >5 people and removing people who did not contribute anything in past 12-24 months (this is fine, people lose interest, new people join, churn is healthy).

Just done this today, should be fine for a while.

**Comment by tinytb** [comment]
@SgtPooki with @lidel 's explanation, would you be able to remove inactive people the next time this happens?

Just want to take the recurring task off lidel's plate, if possible.

**Comment by SgtPooki** [comment]
@tinytb Absolutely. I just wanted to make this an issue so that I could get an update from Lidel on how to handle it since it hadn't come up before. Now, we have it documented. Thanks a ton for stepping back in to assist Lidel!
